<?php
/**
 * @var $this \PackagedUI\PageletsDemo\Layout\Layout
 */

use Packaged\Dispatch\Dispatch;
use Packaged\Dispatch\ResourceStore;

?>
<!doctype html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <?= Dispatch::instance()->store()->generateHtmlIncludes(ResourceStore::TYPE_CSS) ?>
</head>
<body class="demo-page">

<div>
  <button href="/text" data-target="container">page 1 (text)</button>
  <button href="/html" data-target="container">page 2 (html)</button>
  <button href="/pagelet" data-target="container">page 3 (json)</button>
  <button href="#test" data-target="container">hash only (does nothing)</button>
  <button id="custom-request">Custom + Meta</button>
  <a href="/">reload</a>
</div>

<label>
  Other Content: <span id="other">none</span>
</label>
<div id="container">
  <?= $this->getContent(); ?>
</div>


<?= Dispatch::instance()->store()->generateHtmlIncludes(ResourceStore::TYPE_JS); ?>
</body>
</html>
